import os
import requests
import tweepy
import random
import google.generativeai as genai  # ✅ التصحيح 1
import cohere
from tenacity import retry, stop_after_attempt, wait_fixed
import logging
import hashlib
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure APIs
genai.configure(api_key=os.getenv('GEMINI_KEY'))  # ✅ التصحيح 2

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

LAST_HASH_FILE = "last_hash.txt"

def get_content_hash(text):
    return hashlib.md5(text.encode('utf-8')).hexdigest()[:8]

def is_duplicate(content):
    current_hash = get_content_hash(content)
    if os.path.exists(LAST_HASH_FILE):
        with open(LAST_HASH_FILE, "r") as f:
            last_hash = f.read().strip()
        if current_hash == last_hash:
            logging.info(f"Duplicate content detected with hash: {current_hash}")
            return True
    with open(LAST_HASH_FILE, "w") as f:
        f.write(current_hash)
    return False

@retry(stop=stop_after_attempt(3), wait=wait_fixed(2))
def generate_tech_content():
    """Fetches news and generates a summarized tip using Cohere and Gemini."""
    try:
        tavily_key = os.getenv('TAVILY_KEY')
        cohere_key = os.getenv('COHERE_API_KEY')
        gemini_key = os.getenv('GEMINI_KEY')
        
        if not tavily_key or not cohere_key or not gemini_key:
            raise ValueError("TAVILY_KEY, COHERE_API_KEY, or GEMINI_KEY environment variables not set.")

        # --- STEP 1: Get raw content using Tavily (Data Source) ---
        response = requests.post(  # ✅ التصحيح 3
            "https://api.tavily.com/search",
            json={
                "api_key": tavily_key,
                "query": "newest verified AI tools and smartphone hacks Jan 2026",
                "max_results": 3,
                "include_answer": False,
                "search_depth": "basic"
            },
            timeout=10
        )
        response.raise_for_status()
        search_res = response.json()

        if not search_res.get('results'):
            raise Exception("No results found from Tavily API.")

        news = random.choice(search_res['results'])
        content_text = news.get('content') or news.get('snippet', '')
        source_url = news.get('url', 'N/A')
        
        logging.info(f"Raw content fetched from URL: {source_url}")

        # --- STEP 2: Summarize in English using COHERE (Initial Processing) ---
        co = cohere.Client(api_key=os.getenv('COHERE_API_KEY'))  # ✅ التصحيح 4
        cohere_prompt = f"Summarize the following tech article snippet into a very concise English summary suitable for a tech tip: {content_text}"
        
        cohere_response = co.chat(
            model="command-r-plus",
            message=cohere_prompt,
        )
        english_summary = cohere_response.text.strip()
        logging.info(f"English summary generated by Cohere: {english_summary[:50]}...")

        # --- STEP 3: Translate/Refine into Arabic using GEMINI (Final Formatting) ---
        model = genai.GenerativeModel('gemini-2.5-flash')  # ✅ التصحيح 5
        gemini_prompt = f"Translate the following English tech summary into a short, engaging Arabic phrase suitable for a Twitter post (under 200 characters): {english_summary}"
        
        gemini_response = model.generate_content(gemini_prompt)  # ✅ التصحيح 6
        
        final_arabic_content = gemini_response.text.strip()
        if not final_arabic_content:
            raise Exception("Gemini returned empty content.")

        return final_arabic_content, source_url

    except Exception as e:
        logging.error(f"Error within generate_tech_content: {e}")
        raise Exception(f"Failed to fetch or process content: {e}")

def run_mission():
    logging.info("🚀 بدء محاولة النشر النهائية باستخدام Gemini و Cohere...")
    try:
        content, source_url = generate_tech_content()
        
        if is_duplicate(content):
            logging.info("✅ تم تجاهل التغريدة (مكررة).")
            return

       client = tweepy.Client(bearer_token=os.getenv('X_BEARER_TOKEN'))

        max_tweet_length = 280
        link_length = len(source_url)
        content_max_len = max_tweet_length - link_length - 20 

        tweet_text = f"🛡️ موثوق | {content[:content_max_len]}\n\n🔗 {source_url}"
        
        if len(tweet_text) > max_tweet_length:
            tweet_text = tweet_text[:max_tweet_length - len(source_url) - 5] + '... 🔗 ' + source_url

        logging.info(f"Attempting to post tweet of length {len(tweet_text)}.")

        response = client.create_tweet(text=tweet_text)

        if response.data:
            logging.info(f"✅ تم النشر بنجاح! Tweet ID: {response.data['id']}")
        else:
            logging.warning("⚠️ Script completed, but X did not confirm the post.")

    except Exception as e:
        logging.error(f"❌ A precise technical error occurred: {e}")

if __name__ == "__main__":
    run_mission()

