name: Tech AI Bot Reply Service

on:
  push:
    branches: [ main ]  # يعمل عند رفع الكود لفرع main
  schedule:
    - cron: '*/15 * * * *' # يعمل تلقائياً كل 15 دقيقة للتحقق من وجود منشن جديد
  workflow_dispatch:      # يسمح لك بتشغيل البوت يدوياً من واجهة GitHub

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tech AI Bot
        env:
          # ربط الأسرار المخزنة في GitHub بمتغيرات البيئة في الكود
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
        run: python src/reply_agent.py
